const STORAGE_KEY = 'roamly-data-v1';
const seed = { vehicles: [
  {id:'VH-1042', make:'Toyota', model:'Corolla Hybrid', year:'2023', type:'Economy', price:'42', status:'available', color:'green', image:'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=900&q=80'},
  {id:'VH-1047', make:'Volkswagen', model:'T-Roc', year:'2024', type:'Compact SUV', price:'68', status:'rented', color:'blue', image:'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=80'},
  {id:'VH-1051', make:'Audi', model:'A4 Avant', year:'2023', type:'Premium', price:'95', status:'service', color:'orange', image:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=80'},
  {id:'VH-1058', make:'Tesla', model:'Model 3', year:'2024', type:'Electric', price:'88', status:'available', color:'silver', image:'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=900&q=80'},
  {id:'VH-1062', make:'Volvo', model:'XC40', year:'2023', type:'Compact SUV', price:'76', status:'available', color:'blue', image:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=80'},
  {id:'VH-1068', make:'Kia', model:'Sportage', year:'2024', type:'SUV', price:'72', status:'rented', color:'green', image:'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=80'}
], bookings: [
  {id:'BK-02841', customer:'Maya Chen', initials:'MC', vehicle:'Toyota Corolla Hybrid', vehicleId:'VH-1042', dates:'Sep 12 – Sep 15', total:'$126', status:'active'},
  {id:'BK-02840', customer:'Noah Williams', initials:'NW', vehicle:'Volkswagen T-Roc', vehicleId:'VH-1047', dates:'Sep 12 – Sep 18', total:'$408', status:'confirmed'},
  {id:'BK-02839', customer:'Olivia Brown', initials:'OB', vehicle:'Tesla Model 3', vehicleId:'VH-1058', dates:'Sep 11 – Sep 14', total:'$264', status:'active'},
  {id:'BK-02838', customer:'Ethan Davis', initials:'ED', vehicle:'Volvo XC40', vehicleId:'VH-1062', dates:'Sep 08 – Sep 10', total:'$152', status:'completed'},
  {id:'BK-02837', customer:'Sofia Patel', initials:'SP', vehicle:'Audi A4 Avant', vehicleId:'VH-1051', dates:'Sep 07 – Sep 09', total:'$190', status:'completed'}
], customers: [
  {id:'CU-0901', name:'Maya Chen', initials:'MC', email:'maya.chen@email.com', phone:'+1 415 203 1842', bookings:4, spent:'$682', last:'Sep 12, 2024'},
  {id:'CU-0902', name:'Noah Williams', initials:'NW', email:'noah.w@email.com', phone:'+1 312 555 0182', bookings:2, spent:'$408', last:'Sep 12, 2024'},
  {id:'CU-0903', name:'Olivia Brown', initials:'OB', email:'olivia.b@email.com', phone:'+1 646 555 0191', bookings:6, spent:'$1,204', last:'Sep 11, 2024'}
]};
let data = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null') || seed;
if (data.customers.length > 3) { data.customers = data.customers.slice(0, 3); localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); }
const $ = (selector, parent=document) => parent.querySelector(selector);
const $$ = (selector, parent=document) => [...parent.querySelectorAll(selector)];
const save = () => localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
const initials = name => name.split(' ').map(word => word[0]).join('').slice(0,2).toUpperCase();
const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const statusLabel = status => ({available:'Available',rented:'Rented',service:'In service',confirmed:'Confirmed',active:'Active',completed:'Completed'}[status] || status);
function showToast(message){$('#toastMessage').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function navigate(page){const current=page || location.hash.slice(1) || 'dashboard';const valid=['dashboard','fleet','bookings','customers'];const target=valid.includes(current)?current:'dashboard';valid.forEach(name=>$('#'+name+'Page').classList.toggle('hidden',name!==target));$$('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.page===target));$('#breadcrumbPage').textContent=target[0].toUpperCase()+target.slice(1);if(location.hash.slice(1)!==target) history.replaceState(null,'','#'+target);renderAll()}
function renderAll(){renderMetrics();renderFleet();renderBookings();renderCustomers();renderActivity();renderUpcoming();$('#fleetCount').textContent=data.vehicles.length;$('#allFleetCount').textContent=data.vehicles.length;$('#bookingCount').textContent=data.bookings.length}
function renderMetrics(){$('#activeMetric').textContent=data.bookings.filter(b=>b.status==='active').length;$('#attentionMetric').textContent=data.vehicles.filter(v=>v.status==='service').length}
function renderActivity(){const activities=[['MC','Maya Chen','completed a booking','Toyota Corolla Hybrid','8 min ago','green'],['AS','Alex Smith','added a new vehicle','Tesla Model 3','42 min ago','peach'],['NW','Noah Williams','confirmed a booking','Volkswagen T-Roc','1 hr ago','blue']];$('#activityList').innerHTML=activities.map(a=>`<div class="activity-item"><div class="activity-avatar ${a[5]}" style="background:${a[5]==='green'?'#dcefe5':a[5]==='peach'?'#f9dfd0':'dce8f5'}">${a[0]}</div><div class="activity-copy"><strong>${a[1]}</strong> ${a[2]}<span>${a[3]}</span></div><span class="activity-time">${a[4]}</span></div>`).join('')}
function bookingRow(b){return `<tr><td><span class="booking-id">${esc(b.id)}</span></td><td><div class="customer-cell"><span class="mini-avatar">${esc(b.initials)}</span>${esc(b.customer)}</div></td><td><span class="vehicle-name">${esc(b.vehicle)}<small>${esc(b.vehicleId)}</small></span></td><td><span class="date-cell">${esc(b.dates)}</span></td><td><strong>${esc(b.total)}</strong></td><td><span class="status ${b.status}">${statusLabel(b.status)}</span></td><td><button class="row-menu" data-edit="booking" data-id="${b.id}" aria-label="Edit booking">•••</button></td></tr>`}
function renderUpcoming(){$('#upcomingTable').innerHTML=data.bookings.slice(0,3).map(bookingRow).join('')}
function renderBookings(){const term=($('#bookingSearch')?.value||'').toLowerCase();const filter=$('.filter-button.active[data-booking-filter]')?.dataset.bookingFilter||'all';const list=data.bookings.filter(b=>(filter==='all'||b.status===filter)&&Object.values(b).join(' ').toLowerCase().includes(term));$('#bookingsTable').innerHTML=list.length?list.map(bookingRow).join(''):`<tr><td colspan="7" class="empty-state">No bookings match your search.</td></tr>`}
function renderFleet(){const term=($('#fleetSearch')?.value||'').toLowerCase();const filter=$('.filter-button.active[data-fleet-filter]')?.dataset.fleetFilter||'all';const list=data.vehicles.filter(v=>(filter==='all'||v.status===filter)&&Object.values(v).join(' ').toLowerCase().includes(term));$('#fleetGrid').innerHTML=list.length?list.map(v=>`<article class="fleet-card"><div class="car-photo"><img src="${v.image}" alt="${esc(v.make+' '+v.model)}" /><span class="status ${v.status==='rented'?'active':''} ${v.status==='service'?'completed':''}">${statusLabel(v.status)}</span></div><div class="car-info"><h3>${esc(v.make)} ${esc(v.model)}</h3><p>${esc(v.year)} · ${esc(v.type)} · ${esc(v.id)}</p><div class="car-meta"><span>Daily rate <span class="car-price"><strong>$${esc(v.price)}</strong> / day</span></span><span>● ${esc(v.color)}</span></div><div class="card-actions"><button class="small-button" data-edit="vehicle" data-id="${v.id}">Edit vehicle</button><button class="small-button delete" data-delete="vehicle" data-id="${v.id}">Delete</button></div></div></article>`).join(''):`<div class="empty-state">No vehicles match your search.</div>`}
function renderCustomers(){const term=($('#customerSearch')?.value||'').toLowerCase();const list=data.customers.filter(c=>Object.values(c).join(' ').toLowerCase().includes(term));$('#customerSummary').textContent=`${list.length} total customers`;$('#customersTable').innerHTML=list.length?list.map(c=>`<tr><td><div class="customer-cell"><span class="mini-avatar">${esc(c.initials)}</span>${esc(c.name)}</div></td><td><span>${esc(c.email)}<small class="vehicle-name">${esc(c.phone)}</small></span></td><td>${c.bookings}</td><td><strong>${esc(c.spent)}</strong></td><td>${esc(c.last)}</td><td><button class="row-menu" data-edit="customer" data-id="${c.id}" aria-label="Edit customer">•••</button><button class="row-menu" data-delete="customer" data-id="${c.id}" aria-label="Delete customer">×</button></td></tr>`).join(''):`<tr><td colspan="6" class="empty-state">No customers match your search.</td></tr>`}
function formFields(type, item={}){const vehicleFields=`<div class="form-field"><label>Make</label><input name="make" value="${esc(item.make)}" required></div><div class="form-field"><label>Model</label><input name="model" value="${esc(item.model)}" required></div><div class="form-field"><label>Year</label><input name="year" type="number" value="${esc(item.year||2024)}" required></div><div class="form-field"><label>Type</label><select name="type"><option>Economy</option><option>Compact SUV</option><option>Premium</option><option>Electric</option><option>SUV</option></select></div><div class="form-field"><label>Daily rate ($)</label><input name="price" type="number" value="${esc(item.price||50)}" required></div><div class="form-field"><label>Status</label><select name="status"><option value="available">Available</option><option value="rented">Rented</option><option value="service">In service</option></select></div>`;const customerFields=`<div class="form-field full"><label>Full name</label><input name="name" value="${esc(item.name)}" required></div><div class="form-field"><label>Email</label><input name="email" type="email" value="${esc(item.email)}" required></div><div class="form-field"><label>Phone</label><input name="phone" value="${esc(item.phone)}" required></div>`;const bookingFields=`<div class="form-field"><label>Customer</label><input name="customer" value="${esc(item.customer)}" required></div><div class="form-field"><label>Vehicle</label><select name="vehicleId">${data.vehicles.map(v=>`<option value="${v.id}" ${item.vehicleId===v.id?'selected':''}>${esc(v.make+' '+v.model)}</option>`).join('')}</select></div><div class="form-field"><label>Pickup date</label><input name="pickup" type="date" required></div><div class="form-field"><label>Return date</label><input name="return" type="date" required></div><div class="form-field"><label>Total ($)</label><input name="total" type="number" value="${esc((item.total||'$0').replace('$',''))}" required></div><div class="form-field"><label>Status</label><select name="status"><option value="confirmed">Confirmed</option><option value="active">Active</option><option value="completed">Completed</option></select></div>`;return `<div class="form-grid">${type==='vehicle'?vehicleFields:type==='customer'?customerFields:bookingFields}</div><div class="form-actions"><button type="button" class="small-button" id="cancelModal">Cancel</button><button class="primary-button" type="submit">Save ${type}</button></div>`}
let modalType='', editingId=null;
function openModal(type,id=null){modalType=type;editingId=id;const collection=type==='vehicle'?'vehicles':type==='customer'?'customers':'bookings';const item=id?data[collection].find(record=>record.id===id):{};$('#modalEyebrow').textContent=id?'Edit record':'Add record';$('#modalTitle').textContent=`${id?'Edit':'New'} ${type}`;$('#modalSubtitle').textContent=id?'Update the details below and save your changes.':'Add the details below to keep your records up to date.';$('#recordForm').innerHTML=formFields(type,item);$('#recordForm').querySelectorAll('select').forEach(select=>{if(item[select.name])select.value=item[select.name]});$('#modalBackdrop').classList.remove('hidden');$('#recordForm input')?.focus()}
function closeModal(){$('#modalBackdrop').classList.add('hidden')}
function submitForm(event){event.preventDefault();const values=Object.fromEntries(new FormData(event.target));const collection=modalType==='vehicle'?'vehicles':modalType==='customer'?'customers':'bookings';if(modalType==='booking'){const vehicle=data.vehicles.find(v=>v.id===values.vehicleId);values.vehicle=vehicle?`${vehicle.make} ${vehicle.model}`:'';values.initials=initials(values.customer);values.dates=`${values.pickup} – ${values.return}`;values.total=`$${values.total}`;delete values.pickup;delete values.return}if(modalType==='customer'){values.initials=initials(values.name);values.bookings=editingId?(data.customers.find(c=>c.id===editingId)?.bookings||0):0;values.spent=editingId?(data.customers.find(c=>c.id===editingId)?.spent||'$0'):'$0';values.last=editingId?(data.customers.find(c=>c.id===editingId)?.last||'—'):'—'}if(editingId){const index=data[collection].findIndex(record=>record.id===editingId);data[collection][index]={...data[collection][index],...values}}else{const prefix=modalType==='vehicle'?'VH':modalType==='customer'?'CU':'BK';values.id=`${prefix}-${String(Math.floor(Math.random()*9000)+1000)}`;data[collection].unshift(values)}save();closeModal();renderAll();showToast(`${modalType[0].toUpperCase()+modalType.slice(1)} saved successfully`)}
function deleteRecord(type,id){if(!confirm(`Delete this ${type}? This action cannot be undone.`))return;const collection=type==='vehicle'?'vehicles':type==='customer'?'customers':'bookings';data[collection]=data[collection].filter(item=>item.id!==id);save();renderAll();showToast(`${type[0].toUpperCase()+type.slice(1)} deleted`)}
document.addEventListener('click',event=>{const pageLink=event.target.closest('[data-page-link]');if(pageLink){event.preventDefault();navigate(pageLink.dataset.pageLink);return}const open=event.target.closest('[data-open-modal]');if(open){openModal(open.dataset.openModal);return}const edit=event.target.closest('[data-edit]');if(edit){openModal(edit.dataset.edit,edit.dataset.id);return}const del=event.target.closest('[data-delete]');if(del){deleteRecord(del.dataset.delete,del.dataset.id);return}if(event.target.closest('#closeModal')||event.target.closest('#cancelModal')||event.target=== $('#modalBackdrop'))closeModal();const fleetFilter=event.target.closest('[data-fleet-filter]');if(fleetFilter){$$('[data-fleet-filter]').forEach(btn=>btn.classList.remove('active'));fleetFilter.classList.add('active');renderFleet()}const bookingFilter=event.target.closest('[data-booking-filter]');if(bookingFilter){$$('[data-booking-filter]').forEach(btn=>btn.classList.remove('active'));bookingFilter.classList.add('active');renderBookings()}});
document.addEventListener('input',event=>{if(event.target.id==='fleetSearch')renderFleet();if(event.target.id==='bookingSearch')renderBookings();if(event.target.id==='customerSearch')renderCustomers()});document.addEventListener('submit',submitForm);window.addEventListener('hashchange',()=>navigate());$$('[data-page]').forEach(link=>link.addEventListener('click',()=>navigate(link.dataset.page)));navigate();